### PR TITLE
Finished feature/useLandmask.

### LINKED ISSUE #40: Use land mask when initializing bump
use the land mask when initializing BUMP horizontal convolution.

### PR DESCRIPTION
**Pull request by loganchen39**
@travissluka Passed all tests. The problem is we need to update staticbinit.ref, var.ref etc. accordingly. 

Close #40 .

### CODE REVIEW

**Comment by travissluka** [comment]
you need to add the landmask to the geometry sections of var, dirac, and staticbinit.
I have no idea what BUMP is using for the mask if we are not providing it one. I would have thought it would throw and error but I guess not.

**Comment by travissluka** [comment]
...look at the output of the dirac to make sure it is working correctly, there should be no increment over land

**Comment by loganchen39** [comment]
@travissluka Now it works and there's no increment over land, please check and approve.

**Comment by travissluka** [comment]
my ctests are failing due to slightly different answers. When is the last time you updated your jedi repos? There have been some changes to SABER in the past couple of weeks that cause slightly different answers when using a mask. Can you run `make update`, rebuild `umdsst` and make sure the reference files are correct

**Comment by loganchen39** [comment]
Ok, let me try.

**Comment by loganchen39** [comment]
@travissluka Now it should work. Please check and approve.

**Review by travissluka — APPROVED** [review]
Good, as long as the TravisCI tests pass, I haven't had a chance to retest on my computer

**Pull request merged**
