### PR TITLE
Feature/experiment - Added some initial background of 0.25x0.25 grid.

### LINKED ISSUE #72: JEDI test for 0.25x0.25 grid
@travissluka  I reproduced your initial JEDI test, it's pretty fast on Cheyenne, taking about 5 minutes with 1 node (36 processors) to finished 1 month run.

Now I'll try to test for 0.25x0.25 grid, I've uploaded the initial background file "20080101_regridded_sst.nc" and the landmask.nc files at my feature/test branch. Please help check if they are ok when you get a minute.

### PR DESCRIPTION
**Pull request by loganchen39**
@travissluka  I haven't combined your latest PR of "#76 support for modules with new ecbuild", hope there won't be any conflict. 

Close #72 .

### CODE REVIEW

**Comment by travissluka** [comment]
could you please rename the files so that it is clear which ones are 1/4 deg and which ones are 1 deg

**Comment by loganchen39** [comment]
> could you please rename the files so that it is clear which ones are 1/4 deg and which ones are 1 deg

I just renamed these files. Hopefully now it's ok.

**Comment by loganchen39** [comment]
It's not passing the test, I'll update the latest develop branch and re-commit again.

**Comment by travissluka** [comment]
@loganchen39 the tests are failing because you renamed the files but you didn't change names of those files inside the `test/testinput/` yaml files

**Comment by loganchen39** [comment]
@travissluka After combining your latest develop to my working feature/experiment branch, it failed to compile, gonna take a while to figure it out. Previously I tried to use latest ecbuild on Cheyenne and had problems with compiling.

**Comment by travissluka** [comment]
you haven't updated this file https://github.com/UMD-AOSC/UMD-SST/blob/bd98627119235e740ff817ea5b136a174274f761/test/CMakeLists.txt#L23

That previous PR should work for either the new ecbuild or the current. Please test these out when I issue the PRs, part of the reason for getting your approval is to make sure things work for you.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
